### ISSUE TITLE
Cordova WKWebView@1.0.1 and Camera@2 iOS 9 photo glitch

### ISSUE THREAD

**Issue by deadlyfingers** [thaliproject/postcardapp#104]
Sometimes after taking a photo and tapping 'Use Photo' results in being stuck in a white screen.
Error log:

```
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
Communications error: <OS_xpc_error: <error: 0x19bae4af0> { count = 1, contents =
    "XPCErrorDescription" => <string: 0x19bae4e50> { length = 22, contents = "Connection interrupted" }
}>
```

Using iOS9 on iPhone 6+. Worth noting this bug did not occur with Camera@1 plugin and UIWebView

**Comment by deadlyfingers** [comment]
This is a very strange bug as it happens now and again while testing and am having trouble recreating reliably. I'm looking for certain conditions that might trigger it for example: 
- if debugging in Safari
- if soft keyboard is up and camera function is activated

I've submitted the camera@2 iOS issue here:
https://issues.apache.org/jira/browse/CB-10179

**Comment by deadlyfingers** [comment]
We might use HTML5 instead to capture images #105

**Comment by deadlyfingers** [comment]
Fixed in Cordova camera@2.1.0 plugin update - 
https://cordova.apache.org/news/2016/01/19/plugins-release.html

**Comment by jpike88** [comment]
This was not fixed, that bug fix is regarding an actual app crash, not the WKWebView white screen issue.

**Comment by jpike88** [comment]
Relevant:

https://github.com/Telerik-Verified-Plugins/WKWebView/issues/41

**Comment by jaredgreener** [comment]
This is an error for us as well -- crashes everytime the camera opens with this error:

Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2016-05-13 16:46:39.215 SalesRoutes[910:104605] Communications error: <OS_xpc_error: <error: 0x3747f654> { count = 1, contents =
    "XPCErrorDescription" => <string: 0x3747f854> { length = 22, contents = "Connection interrupted" }
}>

Seems to only happen on my iPad mini and not iPad air

**Comment by marcorivm** [comment]
I think I'm having the same issue, did you managed to fix it?

**Comment by yaronyg** [comment]
Alas we haven't touched this code in many months. We are trying to get the underlying system to actually work first. :)
